# Generated by Django 6.1 on 2026-09-29 07:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_add_fees_due_to_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=20)),
                (
                    "sender_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INBOUND", "Inbound (User -> School)"),
                            ("OUTBOUND", "Outbound (School -> User)"),
                        ],
                        db_index=True,
                        default="INBOUND",
                        max_length=10,
                    ),
                ),
                ("message_type", models.CharField(default="text", max_length=30)),
                ("text_content", models.TextField(blank=True, null=True)),
                ("media_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(default="RECEIVED", max_length=50)),
                (
                    "whatsapp_message_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "message_log",
                    models.ForeignKey(
                        blank=True,
                        db_column="message_log_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="api.messagelog",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_column="student_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to="api.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
